### ISSUE TITLE
Error adding library for server-side rendering

### ISSUE THREAD

**Issue by halfninja** [FortAwesome/Font-Awesome#12111]
Following the [guide for server-side rendering](https://fontawesome.com/how-to-use/server-side-rendering), the call to `fontawesome.library.add(solid)` fails:
```
    var expanded = !!icon.icon;
                          ^
TypeError: Cannot read property 'icon' of undefined
    at C:\code\metalsmith\examples\static-site\node_modules\@fortawesome\fontawesome\index.js:1423:27
    at Array.reduce (<anonymous>)
    at define (C:\code\metalsmith\examples\static-site\node_modules\@fortawesome\fontawesome\index.js:1421:39)
    at C:\code\metalsmith\examples\static-site\node_modules\@fortawesome\fontawesome\index.js:1470:9
    at Array.forEach (<anonymous>)
    at Library.add (C:\code\metalsmith\examples\static-site\node_modules\@fortawesome\fontawesome\index.js:1468:30)
    at Object.<anonymous> (C:\code\metalsmith\examples\static-site\helpers.js:6:21)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\code\metalsmith\examples\static-site\index.js:6:1)
    at Module._compile (module.js:643:30)
```
Running in Windows 10 PowerShell, Node 8.9.4, 
"@fortawesome/fontawesome": "^1.1.2",
"@fortawesome/fontawesome-free-solid": "^5.0.4",

**Comment by robmadole** [comment]
We have this fixed in the build system. We should get a release of this out today soon.
