### ISSUE TITLE
An error occurred while installing therubyracer (0.12.2) on Ubuntu16.04 

### ISSUE THREAD

**Issue by sandipmgiri** [FortAwesome/Font-Awesome#12426]
Trying to build Font-Awesome package on Ubuntu16.04 ppc64le using steps mentioned here - https://github.com/FortAwesome/Font-Awesome/tree/v4.7.0

However I am getting below errors for "bundle install" command :

```
$  bundle install

Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this
machine.
Fetching gem metadata from https://rubygems.org/...........
Using blankslate 2.1.2.4
Using bundler 1.16.1
Using fast-stemmer 1.0.2
Using colorator 0.1
Using highline 1.6.21
Using commonjs 0.2.7
Using ffi 1.9.10
Using liquid 2.5.5
Using rb-fsevent 0.9.6
Using maruku 0.7.0
Using posix-spawn 0.3.11
Using yajl-ruby 1.1.0
Using redcarpet 2.3.0
Using safe_yaml 1.0.4
Using libv8 3.16.14.15
Using ref 2.0.0
Using sass 3.4.19
Using parslet 1.5.0
Using classifier 1.3.4
Using commander 4.1.6
Using less 2.5.1
Using rb-inotify 0.9.5
Using rb-kqueue 0.2.4
Using pygments.rb 0.5.4
Fetching therubyracer 0.12.2
Using toml 0.1.2
Using listen 1.3.1
Using jekyll 1.5.1
Installing therubyracer 0.12.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.3 extconf.rb
checking for main() in -lpthread... yes
checking for v8.h... yes
checking for main() in -lv8... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling accessor.cc
compiling array.cc
compiling backref.cc
compiling constants.cc
compiling constraints.cc
compiling context.cc
In file included from context.cc:1:0:
context.cc: In static member function 'static VALUE rr::Context::SetEmbedderData(VALUE, VALUE, VALUE)':
context.cc:81:23: error: 'class v8::Context' has no member named 'SetEmbedderData'
   Void(Context(self)->SetEmbedderData(NUM2INT(index), Value(data)));
                       ^
rr.h:33:20: note: in definition of macro 'Void'
 #define Void(expr) expr; return Qnil;
                    ^
context.cc: In static member function 'static VALUE rr::Context::GetEmbedderData(VALUE, VALUE)':
context.cc:85:23: error: 'class v8::Context' has no member named 'GetEmbedderData'
   Void(Context(self)->GetEmbedderData(NUM2INT(index)));
                       ^
rr.h:33:20: note: in definition of macro 'Void'
 #define Void(expr) expr; return Qnil;
                    ^
Makefile:207: recipe for target 'context.o' failed
make: *** [context.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/www/staging/shared/bundle/ruby/2.3.0/gems/therubyracer-0.12.2 for inspection.
Results logged to /var/www/staging/shared/bundle/ruby/2.3.0/extensions/powerpc64le-linux/2.3.0/therubyracer-0.12.2/gem_make.out

An error occurred while installing therubyracer (0.12.2), and Bundler cannot continue.
Make sure that `gem install therubyracer -v '0.12.2'` succeeds before bundling.

In Gemfile:
  therubyracer
```

Any helps appreciated. Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could I ask you why you need to hack with FA 4.7.0? FA 4 is in EOL

I think this is the wrong repository to report this issue

I'm going to close here, but since I'm a RoR developer I would suggest you to try with Ruby 2.5 and run bundle update instead of bundle install.

Also, feel free to keep commenting

**Comment by sandipmgiri** [comment]
With Ruby 2.5 . I' getting below error -

```
$bundle update

Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching blankslate 2.1.2.4
Installing blankslate 2.1.2.4
Using bundler 1.16.1
Fetching fast-stemmer 1.0.2
Installing fast-stemmer 1.0.2 with native extensions
Fetching classifier 1.3.4
Installing classifier 1.3.4
Fetching colorator 0.1
Installing colorator 0.1
Fetching highline 1.6.21
Installing highline 1.6.21
Fetching commander 4.1.6
Installing commander 4.1.6
Fetching commonjs 0.2.7
Installing commonjs 0.2.7
Fetching ffi 1.9.23 (was 1.9.10)
Installing ffi 1.9.23 (was 1.9.10) with native extensions
Fetching liquid 2.5.5
Installing liquid 2.5.5
Fetching rb-fsevent 0.10.2 (was 0.9.6)
Installing rb-fsevent 0.10.2 (was 0.9.6)
Fetching rb-inotify 0.9.10 (was 0.9.5)
Installing rb-inotify 0.9.10 (was 0.9.5)
Fetching rb-kqueue 0.2.5 (was 0.2.4)
Installing rb-kqueue 0.2.5 (was 0.2.4)
Fetching listen 1.3.1
Installing listen 1.3.1
Fetching maruku 0.7.0
Installing maruku 0.7.0
Fetching posix-spawn 0.3.13 (was 0.3.11)
Installing posix-spawn 0.3.13 (was 0.3.11) with native extensions
Fetching yajl-ruby 1.1.0
Installing yajl-ruby 1.1.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.5.0/gems/yajl-ruby-1.1.0/ext/yajl
/usr/local/rvm/rubies/ruby-2.5.0/bin/ruby -r ./siteconf20180228-19204-1wnzv8i.rb extconf.rb
creating Makefile

current directory: /usr/local/rvm/gems/ruby-2.5.0/gems/yajl-ruby-1.1.0/ext/yajl
make "DESTDIR=" clean

current directory: /usr/local/rvm/gems/ruby-2.5.0/gems/yajl-ruby-1.1.0/ext/yajl
make "DESTDIR="
compiling yajl.c
compiling yajl_alloc.c
compiling yajl_buf.c
compiling yajl_encode.c
compiling yajl_ext.c
yajl_ext.c: In function 'yajl_encode_part':
yajl_ext.c:117:21: warning: variable 'status' set but not used [-Wunused-but-set-variable]
     yajl_gen_status status;
                     ^
yajl_ext.c: In function 'yajl_found_hash_key':
yajl_ext.c:291:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
         VALUE stringEncoded = rb_str_new2(buf);
         ^
yajl_ext.c: In function 'rb_yajl_parser_parse':
yajl_ext.c:442:17: warning: variable 'stat' set but not used [-Wunused-but-set-variable]
     yajl_status stat;
                 ^
yajl_ext.c: In function 'rb_yajl_encoder_enable_json_gem_ext':
yajl_ext.c:852:22: error: 'rb_cFixnum' undeclared (first use in this function)
     rb_define_method(rb_cFixnum, "to_json", rb_yajl_json_ext_fixnum_to_json, -1);
                      ^
yajl_ext.c:852:22: note: each undeclared identifier is reported only once for each function it appears in
yajl_ext.c: At top level:
cc1: warning: unrecognized command line option '-Wno-self-assign'
cc1: warning: unrecognized command line option '-Wno-constant-logical-operand'
cc1: warning: unrecognized command line option '-Wno-parentheses-equality'
cc1: warning: unrecognized command line option '-Wno-tautological-compare'
Makefile:241: recipe for target 'yajl_ext.o' failed
make: *** [yajl_ext.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.5.0/gems/yajl-ruby-1.1.0 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.5.0/extensions/powerpc64le-linux/2.5.0/yajl-ruby-1.1.0/gem_make.out

An error occurred while installing yajl-ruby (1.1.0), and Bundler cannot continue.
Make sure that `gem install yajl-ruby -v '1.1.0'` succeeds before bundling.

In Gemfile:
  jekyll was resolved to 1.5.1, which depends on
    pygments.rb was resolved to 0.5.4, which depends on
      yajl-ruby
```

**Comment by tagliala** [comment]
@sandipmgiri 

Sorry, I gave you a bad advice.

Please give another try with ruby 2.2 and `bundle install`

If therubyracer is going to fail again, please try `bundle update therubyracer`

Problem is that those are old version of the gems (yajl-ruby is at 1.3.1 at the moment, 1.1.0 is too old. Jekyll 1.5.1 itself is too old) and maybe there are dependencies locking old version of gems

If you are not able to compile therubyracer on your architecture, you should report those errors to gem maintainers, but at the same time the error should be related to a version of the gem still supported

Also, FA4 is in EOL and FA5 doesn't have this issue anymore, so I ask you again:

> Could I ask you why you need to hack with FA 4.7.0?

**Comment by sandipmgiri** [comment]
Thanks for the reply @tagliala ,

With Ruby2.2 and bundle install getting below error -

```
bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this
machine.
Fetching gem metadata from https://rubygems.org/...........
Using blankslate 2.1.2.4
Using bundler 1.16.1
Using fast-stemmer 1.0.2
Using classifier 1.3.4
Using colorator 0.1
Using highline 1.6.21
Using commander 4.1.6
Using commonjs 0.2.7
Using ffi 1.9.10
Using liquid 2.5.5
Using rb-fsevent 0.9.6
Using rb-inotify 0.9.5
Using rb-kqueue 0.2.4
Using listen 1.3.1
Using maruku 0.7.0
Using posix-spawn 0.3.11
Using yajl-ruby 1.1.0
Using pygments.rb 0.5.4
Using redcarpet 2.3.0
Using safe_yaml 1.0.4
Using parslet 1.5.0
Using toml 0.1.2
Using jekyll 1.5.1
Using less 2.5.1
Fetching libv8 3.16.14.15
Installing libv8 3.16.14.15 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.2.9/gems/libv8-3.16.14.15/ext/libv8
/usr/local/rvm/rubies/ruby-2.2.9/bin/ruby -r ./siteconf20180228-16523-wjmgej.rb extconf.rb
creating Makefile
/usr/local/rvm/gems/ruby-2.2.9/gems/libv8-3.16.14.15/ext/libv8/builder.rb:86:in `setup_python!': libv8 requires python 2 to be installed in order to build, but it is
currently not available (RuntimeError)
        from /usr/local/rvm/gems/ruby-2.2.9/gems/libv8-3.16.14.15/ext/libv8/builder.rb:53:in `build_libv8!'
        from /usr/local/rvm/gems/ruby-2.2.9/gems/libv8-3.16.14.15/ext/libv8/location.rb:24:in `install!'
        from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.2.9/gems/libv8-3.16.14.15 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.2.9/extensions/powerpc64le-linux/2.2.0/libv8-3.16.14.15/gem_make.out

An error occurred while installing libv8 (3.16.14.15), and Bundler cannot continue.
Make sure that `gem install libv8 -v '3.16.14.15'` succeeds before bundling.

In Gemfile:
  therubyracer was resolved to 0.12.2, which depends on
    libv8
```

>> Could I ask you why you need to hack with FA 4.7.0?

Not compulsory to work on FA4 , I will try to build FA5. Can you please provide the build instructions for the same ? Thanks!

**Comment by tagliala** [comment]
> With Ruby2.2 and bundle install getting below error -

Try with `bundle update libv8`. BTW I can't tell if they support the powerpc linux

> I will try to build FA5

I should ask you why you need to build FA5: I need to know that to find a solution for your issue, it is not a criticism.

The new FA master branch contains all the source files, including individual SVG in the repo.

The build process (from SVGs to webfont) is not open source, because it is the same process behind the Pro version

Instead, if you need to run the documentation locally, at the moment it is not possible. Let's use #10474

**Comment by sandipmgiri** [comment]
Hi @tagliala , 
>I should ask you why you need to build FA5

I want to validate FA5 works properly on ppc64le.  But I couldn't find the build steps for FA5.

**Comment by sandipmgiri** [comment]
Hi @tagliala,
> I should ask you why you need to build FA5: I need to know that to find a solution for your issue, it is not a criticism.

As we discussed so far, FA4 is EOL and is not building correctly on ppc64le. Hence as you suggested I am trying FA5. Also we always work on top-of-the-tree version of any open-source package, so thanks to your suggestion, we are moving to the latest code than FA4.

Major difference I observed with FA5 is that all build related files are removed from source code. So, does that mean FA5 is not open source anymore, or meant to be built by community?

Thanks!

**Comment by tagliala** [comment]
> Major difference I observed with FA5 is that all build related files are removed from source code. So, does that mean FA5 is not open source anymore, or meant to be built by community?

Right, the build process is not open source.

Anyway, FA4's build process wasn't open source either: in both versions you have "compiled" font files

**Comment by sandipmgiri** [comment]
@tagliala , Thanks for the information !!
