### ISSUE TITLE
Unable to download from the Pro Repo

### ISSUE THREAD

**Issue by chrisrink** [FortAwesome/Font-Awesome#13215]
starting a few hours ago I been getting CI errors trying to download from the pro CDN. Looking into this. I see that the authorization method has changed from:

.npmrc
`@fortawesome:registry=https://npm.fontawesome.com/2C116866-AAFB-DEAD-BEEF-0F3F2128F53A/`

to:
`
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=2C116866-AAFB-DEAD-BEEF-0F3F2128F53A
`

But I am getting authorization errors in both ways. 
yarn
 `An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/fontawesome-pro-light/-/fontawesome-pro-light-5.0.13.tgz: Request failed \"404 Not Found\"".`

npm 
`
npm ERR! code E404
npm ERR! 404 Not Found: @fortawesome/fontawesome-pro-light@https://registry.npmjs.org/@fortawesome/fontawesome-pro-light/-/fontawesome-pro-light-5.0.13.tgz`

Is this a known issue?

**Comment by chrisrink** [comment]
So I am looking into this some more and I notice that it is going to the `https://registry.npmjs.org` for some reason. Here is the full log.

```
npm install -verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/10.2.1/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '-verbose' ]
npm info using npm@5.6.0
npm info using node@v10.2.1
npm verb npm-session 0b8c3e0ee175aba0
npm info lifecycle fatest@1.0.0~preinstall: fatest@1.0.0
npm http fetch GET 304 https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro-light 901ms (from cache)
npm http fetch GET 304 https://npm.fontawesome.com/@fortawesome%2ffontawesome-common-types 525ms (from cache)
npm verb correctMkdir /Users/chrisrink/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/chrisrink/.npm/_locks/staging-8013dae47f3c737a.lock for /Users/chrisrink/workspace/fatest/node_modules/.staging
http fetch GET 404 https://registry.npmjs.org/@fortawesome/fontawesome-pro-light/-/fontawesome-pro-light-5.0.10.tgz 185ms.10
npm verb unlock done using /Users/chrisrink/.npm/_locks/staging-8013dae47f3c737a.lock for /Users/chrisrink/workspace/fatest/node_modules/.staging
npm WARN fatest@1.0.0 No description
npm WARN fatest@1.0.0 No repository field.

npm verb type Error
npm verb stack Error: 404 Not Found: @fortawesome/fontawesome-pro-light@https://registry.npmjs.org/@fortawesome/fontawesome-pro-light/-/fontawesome-pro-light-5.0.10.tgz
npm verb stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:696:18)
npm verb stack     at tryOnImmediate (timers.js:667:5)
npm verb stack     at processImmediate (timers.js:649:5)
npm verb cwd /Users/chrisrink/workspace/fatest
npm verb Darwin 17.5.0
npm verb argv "/usr/local/Cellar/node/10.2.1/bin/node" "/usr/local/bin/npm" "install" "-verbose"
npm verb node v10.2.1
npm verb npm  v5.6.0
npm ERR! code E404
npm ERR! 404 Not Found: @fortawesome/fontawesome-pro-light@https://registry.npmjs.org/@fortawesome/fontawesome-pro-light/-/fontawesome-pro-light-5.0.10.tgz
```

I have run `npm cache clear` but that doesn't seem to help. I also notice that if I hit the url:
https://npm.fontawesome.com/2C116866-AAFB-DEAD-BEEF-0F3F2128F53A/@fortawesome/fontawesome-pro-light/-/fontawesome-pro-light-5.0.10.tgz that will download properly.

So I am not sure why this redirect is happening.

note  2C116866-AAFB-DEAD-BEEF-0F3F2128F53A is not my real token.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
