### ISSUE TITLE
Site doesn't show icons on Internet Explorer 11

### ISSUE THREAD

**Issue by ASKemp** [FortAwesome/Font-Awesome#14020]
Site doesn't show icons on Internet Explorer 11

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can confirm.

Also, the website is painfully slow and unresponsive.

URL: https://fontawesome.com/icons?d=gallery

Windows 10 64 bit
IE version: 11.285.17134.0

Console output
```
ReferenceError: 'Symbol' non è definito
   {
      [functions]: ,
      __proto__: { },
      description: "'Symbol' non è definito",
      message: "'Symbol' non è definito",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'Symbol' non è definito
   at Q.methods.filters (https://fontawesome.com/js/44.5f72d584765ae569dd91.js:1:16026)
   at hasFilters (https://fontawesome.com/js/44.5f72d584765ae569dd91.js:1:14960)
   at St.prototype.get (https://fontawesome.com/js/app-36fcf0d192420feb6dd6b064027a7d3b.js?vsn=d:13:15711)
   at St.prototype.evaluate (https://fontawesome.com/js/app-36fcf0d192420feb6dd6b064027a7d3b.js?vsn=d:13:16859)
   at Anonymous function (https://fontawesome.com/js/app-36fcf0d192420feb6dd6b064027a7d3b.js?vsn=d:13:17612)
   at Anonymous function (https://fontawesome.com/js/44.5f72d584765ae569dd91.js:1:17653)
   at fn.prototype._render (https://fontawesome.com/js/app-36fcf0d192420feb6dd6b064027a7d3b.js?vsn=d:13:31688)
   at Anonymous function (https://fontawesome.com/js/app-36fcf0d192420feb6dd6b064027a7d3b.js?vsn=d:13:63388)
   at St.prototype.get (https://fontawesome.com/js/app-36fcf0d192420feb6dd6b064027a7d3b.js?vsn=d:13:15711)
   at St (https://fontawesome.com/js/app-36fcf0d192420feb6dd6b064027a7d"
   }

```

**Comment by robmadole** [comment]
I believe this is resolved now.
