### ISSUE TITLE
npm reporting "HPE_HEADER_OVERFLOW" for npm.fontawesome.com

### ISSUE THREAD

**Issue by richardtallent** [FortAwesome/Font-Awesome#16995]
I'm trying to update my various packages, and I'm getting the following error from npm:

```
> npm install --save @fortawesome/fontawesome-free

npm ERR! code HPE_HEADER_OVERFLOW
npm ERR! errno HPE_HEADER_OVERFLOW
npm ERR! request to https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/5.14.0/fontawesome-free-5.14.0.tgz failed, reason: Parse Error: Header overflow
```

My auth key is still saved, and I recently renewed for v6.

My employer recently installed ZScaler, a traffic-monitoring proxy, which I _suspect_ may be involved, since I had to disable strict HTTPS to get it to work with npm's registry, and I'm still having some trouble with some github repos. Nevertheless, this issue is currently limited to the fontawesome registry.

There's some talk on Google about changing node's `max-http-header-size=size`, but I suspect that's a server-side change, not a client-side option that I can control in npm.

**Comment by noelmccrory** [comment]
I am also getting this issue although with the pro version. Coincidentally (maybe) I am also using ZScaler.

Are you using an internal NPM registry?

**Comment by tagliala** [comment]
@robmadole can we do something about this? Maybe follow up via hello@fontawesome.com?

**Comment by richardtallent** [comment]
@noelmccrory, we're not using an internal registry, just npm's public registry for most things and fontawesome's registry for the FA stuff.

**Comment by robmadole** [comment]
@richardtallent yeah, fire me an email to hello@fontwesome.com and ask for me (Rob). Since we are gonna chat security let's not have any more of your private information out here in the public repo.

So couple of questions:

1. If you disable ZScaler does it work? (Can you even test this now that the ship has sailed?)
1. Can you install `@fortawesome/fontawesome-free` from `registry.npmjs.com`? (the public registry, not our private one)
1. Can you get a detailed log from `npm`? There should be a `npm-debug.log` available you can attach to me

Let's start here. We've seen this type of thing once before and it was the misbehaving security appliance causing it (the response was not from npm.fontwesome.com but from the appliance)

**Comment by richardtallent** [comment]
Hi @robmadole,

I disabled ZScaler, and it did indeed work properly.

Then I noticed that I was still running npm 6.12,x, so I went ahead and updated to the latest (6.14.7), and it's **working beautifully** again. I didn't get a chance to test the old npm with registry.npmjs.com and the free FA package, but I was successfully pulling all other packages from that registry, so I wouldn't expect fa-free to be any different.

Maybe @noelmccrory can confirm if they are using an older npm, and if so, if updating npm also fixes it for them?

**Comment by noelmccrory** [comment]
I was running npm 6.14.6. I updated to 6.14.7 and still seeing the issue.

What version of node are you running? I'm running 12.18.2

**Comment by robmadole** [comment]
@richardtallent great to hear!

@noelmccrory might be beneficial to also find out what ZScaler version you are using?

**Comment by noelmccrory** [comment]
![image](https://user-images.githubusercontent.com/11225700/90109027-139fab80-dd43-11ea-8cd9-1c693c00ada1.png)

**Comment by richardtallent** [comment]
And... now it's happening again for me.

npm version: 6.14.7
ZScaler version: 2.1.2.112 (248808)

I've raised a ticket with my internal IT support, but they won't be able to do anything other than confirm the problem.

It's still only an issue with the @fortawesome server. My .npmrc is as follows:

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=SECRET_PRO_CODE_SHHHHHH
```

Here's the verbose npm error log for the command `npm install --save @fortawesome/fontawesome-free`:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Richard.Tallent\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@fortawesome/fontawesome-free'
1 verbose cli ]
2 info using npm@6.14.7
3 info using node@v12.19.0
4 verbose npm-session e454c817d9eb523c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://npm.fontawesome.com/@fortawesome%2ffontawesome-free 617ms (from cache)
8 silly fetchPackageMetaData error for @fortawesome/fontawesome-free@^5.14.0 request to https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/5.15.1/fontawesome-free-5.15.1.tgz failed, reason: Parse Error: Header overflow
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 5926ms
11 verbose type system
12 verbose stack FetchError: request to https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/5.15.1/fontawesome-free-5.15.1.tgz failed, reason: Parse Error: Header overflow
12 verbose stack     at ClientRequest.<anonymous> (C:\Users\Richard.Tallent\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
12 verbose stack     at ClientRequest.emit (events.js:314:20)
12 verbose stack     at TLSSocket.socketOnData (_http_client.js:482:9)
12 verbose stack     at TLSSocket.emit (events.js:314:20)
12 verbose stack     at addChunk (_stream_readable.js:298:12)
12 verbose stack     at readableAddChunk (_stream_readable.js:273:9)
12 verbose stack     at TLSSocket.Readable.push (_stream_readable.js:214:10)
12 verbose stack     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
13 verbose cwd C:\PATH_TO_CLIENT_FOLDER
14 verbose Windows_NT 10.0.17134
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Richard.Tallent\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@fortawesome/fontawesome-free"
16 verbose node v12.19.0
17 verbose npm  v6.14.7
18 error code HPE_HEADER_OVERFLOW
19 error errno HPE_HEADER_OVERFLOW
20 error request to https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/5.15.1/fontawesome-free-5.15.1.tgz failed, reason: Parse Error: Header overflow
21 verbose exit [ 1, true ]
```

**Comment by robmadole** [comment]
@richardtallent do you think this is ZScaler again?

**Comment by noelmccrory** [comment]
I was able to resolve this by adding the following environment variable:

`export NODE_OPTIONS="--max-http-header-size=80000"`

**Comment by ghost** [comment]
@noelmccrory how to?
