### ISSUE TITLE
npm Install Fails.

### ISSUE THREAD

**Issue by nandhakumarsathiya** [FortAwesome/Font-Awesome#17239]
npm install fails with error 
Couldn't find any versions for "@fortawesome/fontawesome-common-types" that matches "^0.2.32"
![image](https://user-images.githubusercontent.com/10941883/95109965-f1cb0f80-075a-11eb-9d40-4958465e1883.png)

**Comment by AdamMYoung** [comment]
Getting this also, looks like they pushed an update out right when this started appearing

**Comment by Zac-Zajdel** [comment]
Unfortunately getting this same issue as well in the midst of pushing a hotfix to production. Reverting to an older version will work if applicable to your project in the meantime.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Probably you deployed in the middle of the 5.15.1 release, when all packages were going to be uploaded on NPM

Please retry now, they should be all there

@robmadole is there anything we can do for this? i.e: scheduled release, first `fontawesome-common-types` (0 deps), then `fontawesome-svg-core` (1 dep, common types) and then the individual icon packages?

**Comment by robmadole** [comment]
Yep, we were right in the middle of the deploy. Can you try again please?

**Comment by Zac-Zajdel** [comment]
The issue has been resolved with retrying the pipeline. Appreciate the response everyone!

**Comment by robmadole** [comment]
Good to hear :+1:

**Comment by JulianNicholls** [comment]
Installing, for example, @fortawesome/free-solid-svg-icons gives errors.

This is from a yarn-error.log

```
Trace:
  Error: https://npm.fontawesome.com/@fortawesome%2ffree-solid-svg-icons: authentication required
      at Request.params.callback [as _callback] (/home/julian/.nvm/versions/node/v14.5.0/lib/node_modules/yarn/lib/cli.js:66988:18)
      at Request.self.callback (/home/julian/.nvm/versions/node/v14.5.0/lib/node_modules/yarn/lib/cli.js:140662:22)
      at Request.emit (events.js:314:20)
      at Request.<anonymous> (/home/julian/.nvm/versions/node/v14.5.0/lib/node_modules/yarn/lib/cli.js:141634:10)
      at Request.emit (events.js:314:20)
      at IncomingMessage.<anonymous> (/home/julian/.nvm/versions/node/v14.5.0/lib/node_modules/yarn/lib/cli.js:141556:12)
      at Object.onceWrapper (events.js:420:28)
      at IncomingMessage.emit (events.js:326:22)
      at endReadableNT (_stream_readable.js:1226:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

and this from an npm debug.log

```
2102 http fetch GET 401 https://npm.fontawesome.com/@fortawesome%2fpro-regular-svg-icons 86ms
2103 silly fetchPackageMetaData error for @fortawesome/pro-regular-svg-icons@^5.13.0 Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
2104 http fetch GET 401 https://npm.fontawesome.com/@fortawesome%2ffontawesome-svg-core 92ms
2105 silly fetchPackageMetaData error for @fortawesome/fontawesome-svg-core@^1.2.28 Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
2106 http fetch GET 401 https://npm.fontawesome.com/@fortawesome%2ffree-solid-svg-icons 94ms
2107 http fetch GET 401 https://npm.fontawesome.com/@fortawesome%2freact-fontawesome 97ms
2108 silly fetchPackageMetaData error for @fortawesome/free-solid-svg-icons@^5.13.0 Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
2109 silly fetchPackageMetaData error for @fortawesome/react-fontawesome@^0.1.10 Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
2110 timing stage:rollbackFailedOptional Completed in 0ms
2111 timing stage:runTopLevelLifecycles Completed in 7749ms
2112 silly saveTree palette-visualiser@5.0.2
2112 silly saveTree ├── normalize.css@8.0.1
2112 silly saveTree ├── prop-types@15.7.2
2112 silly saveTree ├── react-dom@16.13.1
2112 silly saveTree └── react@16.13.1
2113 verbose stack Error: Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
2113 verbose stack     at /home/julian/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:107:17
2113 verbose stack     at runMicrotasks (<anonymous>)
2113 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2114 verbose statusCode 401
2115 verbose pkgid @fortawesome/pro-regular-svg-icons@^5.13.0

```
