### ISSUE TITLE
Error Message when executing 'yarn' command

### ISSUE THREAD

**Issue by harrytodd** [FortAwesome/Font-Awesome#17560]
Tried running 'yarn' in my terminal and get the below error message:

```
yarn install v1.22.5
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffontawesome: authentication required".
info If you think this is a bug, please open a bug report with the information provided in "/Users/harrytodd/x/x/x/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I have the below in my package.json:

    "@fortawesome/fontawesome": "^1.1.5",
    "@fortawesome/fontawesome-free-brands": "^5.0.10",
    "@fortawesome/fontawesome-free-regular": "^5.0.10",
    "@fortawesome/react-fontawesome": "0.0.18"

I have the latest versions of yarn and npm.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Yarn is trying to access the private npm repository, even if you are using Font Awesome Free.

Maybe there is an `.npmrc` somewhere (in the folder tree hierarchy or global .npmrc) instructing yarn to do that

Are you a Pro customer?

**Comment by harrytodd** [comment]
Hi, no I am not, but even if I try to use the free versions I get the same issue.

There is no .npmrc file.

**Comment by tagliala** [comment]
Please run `yarn --verbose` and put here the log, having care of removing any sensitive information (like user name) in the log

**Comment by harrytodd** [comment]
```
yarn install v1.22.5
verbose 0.329430109 Checking for configuration file "/Users/harrytodd/x/x/x/.npmrc".
verbose 0.329812216 Checking for configuration file "/Users/harrytodd/.npmrc".
verbose 0.330097408 Found configuration file "/Users/harrytodd/.npmrc".
verbose 0.331510575 Checking for configuration file "/usr/local/etc/npmrc".
verbose 0.33186692 Checking for configuration file "/Users/harrytodd/x/x/x/.npmrc".
verbose 0.332204584 Checking for configuration file "/Users/harrytodd/development/coding-tests/.npmrc".
verbose 0.333129436 Checking for configuration file "/Users/harrytodd/development/.npmrc".
verbose 0.333440892 Checking for configuration file "/Users/harrytodd/.npmrc".
verbose 0.3336821 Found configuration file "/Users/harrytodd/.npmrc".
verbose 0.334096656 Checking for configuration file "/Users/.npmrc".
verbose 0.335916401 Checking for configuration file "/Users/harrytodd/x/x/x/.yarnrc".
verbose 0.336095991 Checking for configuration file "/Users/harrytodd/.yarnrc".
verbose 0.336222369 Found configuration file "/Users/harrytodd/.yarnrc".
verbose 0.336627742 Checking for configuration file "/usr/local/etc/yarnrc".
verbose 0.336935071 Checking for configuration file "/Users/harrytodd/x/x/x/.yarnrc".
verbose 0.337281204 Checking for configuration file "/Users/harrytodd/development/coding-tests/.yarnrc".
verbose 0.337506047 Checking for configuration file "/Users/harrytodd/development/.yarnrc".
verbose 0.33777392 Checking for configuration file "/Users/harrytodd/.yarnrc".
verbose 0.338120206 Found configuration file "/Users/harrytodd/.yarnrc".
verbose 0.33844491 Checking for configuration file "/Users/.yarnrc".
verbose 0.342559095 current time: 2021-01-15T16:03:44.709Z
info No lockfile found.
[1/4] 🔍  Resolving packages...
verbose 0.410269755 Performing "GET" request to "https://npm.fontawesome.com/@fortawesome%2ffontawesome".
verbose 0.546869599 Request "https://npm.fontawesome.com/@fortawesome%2ffontawesome" finished with status code 401.
verbose 0.556332528 Error: https://npm.fontawesome.com/@fortawesome%2ffontawesome: authentication required
    at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.22.5/libexec/lib/cli.js:66988:18)
    at Request.self.callback (/usr/local/Cellar/yarn/1.22.5/libexec/lib/cli.js:140749:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.5/libexec/lib/cli.js:141721:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.22.5/libexec/lib/cli.js:141643:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffontawesome: authentication required".
info If you think this is a bug, please open a bug report with the information provided in "/Users/harrytodd/x/x/x/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by tagliala** [comment]
```
verbose 0.3336821 Found configuration file "/Users/harrytodd/.npmrc".
verbose 0.336222369 Found configuration file "/Users/harrytodd/.yarnrc".

```

Please check those files and remove occurrences like

```
@fortawesome:registry=https://npm.fontawesome.com/
```

**Comment by harrytodd** [comment]
ah yes!! all working now, thank you :)

**Comment by tagliala** [comment]
Welcome, glad you solved 👍
