### ISSUE TITLE
Can't install pro files via NPM

### ISSUE THREAD

**Issue by coreyog** [FortAwesome/Font-Awesome#17620]
**Describe the bug**
I'm working on a new Angular project and I can't install font-awesome-pro.

**To Reproduce**
Follow the advice on this page: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
Or this bug: https://github.com/FortAwesome/Font-Awesome/issues/12550

I've attempted to use the .npmrc file as well as setting global npm config values. Either approach produces the same output.

**Expected behavior**
The files are downloaded and development can begin using the resources.

**Observed behavior**
$ npm install --save @fortawesome/fontawesome-pro
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/corey.ogburn/.npm/_logs/2021-02-09T19_31_02_270Z-debug.log

**Version and implementation**
$ npm version
{
  npm: '7.5.3',
  node: '15.7.0',
  v8: '8.6.395.17-node.23',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] --I have included a test case because my odds go _way_ up that the team can fix this when I do--
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

Here's the contents of the log file mentioned in the NPM output:

0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/Users/corey.ogburn/.npm-packages/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--save',
0 verbose cli   '@fortawesome/fontawesome-pro'
0 verbose cli ]
1 info using npm@7.5.3
2 info using node@v15.7.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/Users/corey.ogburn/.npm-packages/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/corey.ogburn/go/src/github.com/coreyog/devdiary/.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/Users/corey.ogburn/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session daa073f767a9b4b3
20 timing npm:load Completed in 12ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree:init Completed in 8ms
23 timing idealTree:userRequests Completed in 1ms
24 silly idealTree buildDeps
25 silly fetch manifest @fortawesome/fontawesome-pro@*
26 http fetch GET 401 https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro 376ms
27 silly placeDep ROOT @fortawesome/fontawesome-pro@ OK for:  want: *
28 timing idealTree:#root Completed in 385ms
29 timing idealTree:node_modules/@fortawesome/fontawesome-pro Completed in 0ms
30 timing idealTree:buildDeps Completed in 386ms
31 timing idealTree:fixDepFlags Completed in 0ms
32 timing idealTree Completed in 398ms
33 timing command:install Completed in 407ms
34 verbose stack Error: Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com"
34 verbose stack     at /Users/corey.ogburn/.npm-packages/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:113:17
34 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:94:5)
34 verbose stack     at async Arborist.[nodeFromEdge] (/Users/corey.ogburn/.npm-packages/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:875:19)
34 verbose stack     at async Arborist.[buildDepStep] (/Users/corey.ogburn/.npm-packages/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:825:11)
34 verbose stack     at async Arborist.buildIdealTree (/Users/corey.ogburn/.npm-packages/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
34 verbose stack     at async Promise.all (index 1)
34 verbose stack     at async Arborist.reify (/Users/corey.ogburn/.npm-packages/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:127:5)
34 verbose stack     at async install (/Users/corey.ogburn/.npm-packages/lib/node_modules/npm/lib/install.js:38:3)
35 verbose statusCode 401
36 verbose pkgid @fortawesome/fontawesome-pro@*
37 verbose cwd /Users/corey.ogburn/go/src/github.com/coreyog/devdiary
38 verbose Darwin 19.6.0
39 verbose argv "/usr/local/bin/node" "/Users/corey.ogburn/.npm-packages/bin/npm" "install" "--save" "@fortawesome/fontawesome-pro"
40 verbose node v15.7.0
41 verbose npm  v7.5.3
42 error code E401
43 error Incorrect or missing password.
44 error If you were trying to login, change your password, create an
44 error authentication token or enable two-factor authentication then
44 error that means you likely typed your password in incorrectly.
44 error Please try again, or recover your password at:
44 error     https://www.npmjs.com/forgot
44 error
44 error If you were doing some other operation then your saved credentials are
44 error probably out of date. To correct this please try logging in again with:
44 error     npm login
45 verbose exit 1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please send an email to hello@fontawesome.com?

**Comment by rlueder** [comment]
Stumbled on this same issue and found it all very confusing (long story short, having a license doesn't include the private npm registry, that requires a subscription).

I eventually found a reasonable explanation here: https://github.com/FortAwesome/Font-Awesome/issues/17147#issuecomment-692775989 and an actual solution here: https://fontawesome.com/how-to-use/on-the-web/setup/using-the-npm-download

**Comment by yandodov** [comment]
Just to confirm what @rlueder has said:

<img width="798" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/5570098/9af6dbf2-c531-4835-9c10-cf05285a872a">

This is said in [Using a Package Manager → Private and Public npm Repositories](https://fontawesome.com/docs/web/setup/packages#private-and-public-npm-repositories).
