### ISSUE TITLE
Server Side rendering problem with NextJS and mask prop

### ISSUE THREAD

**Issue by pioz** [FortAwesome/Font-Awesome#18702]
When I add this line of code in my React component using NextJS v12.0.10 
```jsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGithub } from '@fortawesome/free-brands-svg-icons'
import { faCircle } from '@fortawesome/free-solid-svg-icons'

<FontAwesomeIcon fixedWidth icon={faGithub} mask={faCircle} size="2x" transform="shrink-6" />
```

in Chrome console I get this warning:

```
Warning: Prop `id` did not match. Server: "clip-czH9E63zpnkZ" Client: "clip-p0bNRCYkXdjo"
    at clipPath
    at defs
    at svg
    at FontAwesomeIcon (webpack-internal:///./node_modules/@fortawesome/react-fontawesome/index.es.js:336:27)
    at a
    at div
    at Social
    at div
    at div
    at div
    at div
    at Layout (webpack-internal:///./components/Layout.jsx:20:26)
    at Home
    at MyApp (webpack-internal:///./pages/_app.js:38:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:359:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:793:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:915:27) 

```

If I remove the `mask` prop I get no warnings. I know this is only a warning, but is there a way to avoid it?

**Comment by shehi** [comment]
`Prop X didn't not match` error is prevalent in NextJs - but yea, FontAwesome should make sure they are not causing it.

**Comment by tagliala** [comment]
@robmadole could you please take a look?
