### ISSUE TITLE
Bug: error when: import faTrash from '@fortawesome/free-solid-svg-icons'

### ISSUE THREAD

**Issue by kuchaguangjie** [FortAwesome/Font-Awesome#19192]
### Bug description

Import:
```
import {faTrash} from '@fortawesome/free-solid-svg-icons'
```
or

```
import faTrash from '@fortawesome/free-solid-svg-icons'
```

When compile by `vite build`, get error.

Error log:
```
'default' is not exported by node_modules/.pnpm/registry.npmmirror.com+@fortawesome+free-solid-svg-icons@6.1.1/node_modules/@fortawesome/free-solid-svg-icons/index.es.js, imported by src/components/PageList.svelte
file: /mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/src/components/PageList.svelte:7:9
5:   import YesNoDialog from "../components/YesNoDialog.svelte";
6:   import Fa from 'svelte-fa/src/fa.svelte'
7:   import faTrash from '@fortawesome/free-solid-svg-icons'
            ^
8: 
9:   /* exported properties */
error during build:
Error: 'default' is not exported by node_modules/.pnpm/registry.npmmirror.com+@fortawesome+free-solid-svg-icons@6.1.1/node_modules/@fortawesome/free-solid-svg-icons/index.es.js, imported by src/components/PageList.svelte
    at error (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:12411:16)
    at Module.traceVariable (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:12770:29)
    at ModuleScope.findVariable (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:11422:39)
    at FunctionScope.findVariable (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:6355:38)
    at ChildScope.findVariable (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:6355:38)
    at Identifier.bind (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:7422:40)
    at Property.bind (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
    at ObjectExpression.bind (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:5248:73)
    at Property.bind (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+rollup@2.77.0/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
 ELIFECYCLE  Command failed with exit code 1.
```

### Font Awesome version

v6.1.1

### Serving

Kit

### Implementation

CSS

### Browser and Operating System

- Chrome Version 102.0.5005.115 (Official Build) (64-bit)

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Thanks for opening this issue! Since it’s been a while and things have changed quite a bit in Font Awesome since this was originally posted, we’re closing it out to help keep our issue tracker focused on current work.

If this is still important for your project, please feel free to re-open or file a fresh issue with updated details. Thanks so much!
