### ISSUE TITLE
Bug:  Error: Uncaught [TypeError: (0 , import_macro_1.light) is not a function]

### ISSUE THREAD

**Issue by nishanthsinghgurung2** [FortAwesome/Font-Awesome#19468]
### Bug description

I am using a font awesome icon inside an aggrid. This icon is present in all the rows and would help the user to edit the contents of the row.
Icon code is as follows:
<FontAwesomeIcon color="#26b7cd" className="cursor-pointer basket-grid-save" fontSize="20px" fontWeight="300" icon={light('edit')} />

It works fine on UI. However, when I try to write unit test using react testing library it gives the error mentioned below. I can mock this whole icon component to remove the error. However, I would like to grab the icon and click it as part of the test. Please let me know what to do here:

`console.error
    Error: Uncaught [TypeError: (0 , import_macro_1.light) is not a function]
        at reportException (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
        at Timeout.task [as _onTimeout] (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\jsdom\lib\jsdom\browser\Window.js:519:9)
        at listOnTimeout (node:internal/timers:557:17)
        at processTimers (node:internal/timers:500:7) {
      detail: TypeError: (0 , import_macro_1.light) is not a function
          at BtnCellRenderer (C:\Users\singnis\projects\office\PreTradeWeb\src\components\GridComponents\BtnCellRenderer.tsx:33:153)
          at Component (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:14985:18)
          at renderWithHooks (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:17811:13)
          at mountIndeterminateComponent (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:19049:16)
          at HTMLUnknownElement.apply (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:3945:14)
          at HTMLUnknownElement.callTheUserObjectsOperation (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\jsdom\lib\jsdom\living\generated\EventListener.js:26:30)
          at innerInvokeEventListeners (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:340:25)
          at invokeEventListeners (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:276:3)
          at HTMLUnknownElementImpl._dispatch (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:223:9)
          at HTMLUnknownElementImpl.dispatchEvent (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:94:17)
          at HTMLUnknownElement.dispatchEvent (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:241:34)
          at Object.dispatchEvent (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:3994:16)
          at apply (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:4056:31)
          at invokeGuardedCallback (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:23964:7)
          at beginWork$1 (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:22779:12)
          at performUnitOfWork (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:22707:5)
          at workLoopSync (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:22670:7)
          at renderRootSync (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:22293:18)
          at callback (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:11327:26)
          at eventHandler (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\scheduler\cjs\scheduler.development.js:468:12)
          at Scheduler_runWithPriority (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:11276:10)
          at runWithPriority$1 (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:11322:9)
          at flushSyncCallbackQueueImpl (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:11309:3)
          at flushSyncCallbackQueue (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:23620:3)
          at eventHandler (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\scheduler\cjs\scheduler.development.js:468:12)
          at Scheduler_runWithPriority (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:11276:10)
          at runWithPriority$1 (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:23447:14)
          at flushPassiveEffects (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\react-dom\cjs\react-dom.development.js:23324:11)
          at callback (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\scheduler\cjs\scheduler.development.js:417:34)
          at workLoop (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\scheduler\cjs\scheduler.development.js:390:14)
          at _callback (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\scheduler\cjs\scheduler.development.js:55:9)
          at Timeout.task [as _onTimeout] (C:\Users\singnis\projects\office\PreTradeWeb\node_modules\jsdom\lib\jsdom\browser\Window.js:514:19)
          at listOnTimeout (node:internal/timers:557:17)
          at processTimers (node:internal/timers:500:7),
      type: 'unhandled exception'
    }
`

### Font Awesome version

"@fortawesome/fontawesome-svg-core": "^6.1.1",         "@fortawesome/free-solid-svg-icons": "^6.1.1",         "@fortawesome/pro-duotone-svg-icons": "^6.1.1",         "@fortawesome/pro-light-svg-icons": "^6.1.1",         "@fortawesome/pro-regular-svg-icons": "^6.1.1",         "@fortawesome/pro-solid-svg-icons": "^6.1.1",         "@fortawesome/react-fontawesome": "^0.1.18",

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

uses jest to run unit tests using react testing library on windows

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by seeratawan01** [comment]
`TypeError: (0 , import_macro_1.light) is not a function` | `TypeError: (0 , import_macro_1.solid) is not a function`

I'm getting the same errors in my jest test cases, does anyone find a solution or workaround for these issues?
