### ISSUE TITLE
Bug: @fortawesome/free-regular-svg-icons gives a 404 on npm

### ISSUE THREAD

**Issue by AndreMiras** [FortAwesome/Font-Awesome#20495]
### Bug description

https://www.npmjs.com/package/@fortawesome/free-regular-svg-icons

```
yarn add @fortawesome/free-regular-svg-icons@^6
yarn add v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
error Error: https://registry.yarnpkg.com/@fortawesome%2ffree-regular-svg-icons: Not found
    at params.callback [as _callback] (/usr/lib/node_modules/yarn/lib/util/request-manager.js:451:18)
    at self.callback (/usr/lib/node_modules/yarn/node_modules/request/request.js:185:22)
    at Request.emit (node:events:518:28)
    at Request.<anonymous> (/usr/lib/node_modules/yarn/node_modules/request/request.js:1157:10)
    at Request.emit (node:events:518:28)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/yarn/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (node:events:632:28)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command
```

This started happening today around 18:00 UTC, I know it worked earlier on as my CI passed.

![image](https://github.com/user-attachments/assets/5208a125-126e-4799-9408-737a7be733ef)

### Font Awesome version

v6

### Application and Operating System

Arch Linux

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by audacioustux** [comment]
same for @fortawesome/react-fontawesome... https://www.npmjs.com/package/@fortawesome/react-fontawesome?activeTab=versions none of them accessible 
edit: it's npmjs issue... other repos are also down

**Comment by AndreMiras** [comment]
...and it's back!
